### ISSUE TITLE
Multiple Listeners

### ISSUE THREAD

**Issue by marcus433** [whiteout-io/imap-client#37]
Would it be possible to support listening for changes on multiple folders at once?
Thanks!

**Comment by felixhammerl** [comment]
hmm ... well ... you might do this by cycling through folders as soon as you open the second connection in listening mode, most likely with the [STATUS command](https://tools.ietf.org/html/rfc3501#section-6.3.10). patches welcome, but you'd possibly have to patch browserbox, too :)

**Comment by marcus433** [comment]
I attempted to patch this earlier today. The only issue I've ran into is when receiving syncUpdate I cant pair the change with the correct folder as the IMAP connection simply returns the change and not the folder it occurred on. Any ideas?

**Comment by felixhammerl** [comment]
of course it returns the folder the change occurred on: https://github.com/whiteout-io/imap-client/blob/master/src/imap-client.js#L194

**Comment by marcus433** [comment]
yes, but within browserbox that path is simply grabbed from the variable selectedmailbox thus if I were to make an array called selectedMailboxes I wouldn't be able to match the path as all of the paths are determined by that variable



—

**Comment by felixhammerl** [comment]
uh ... uhm ... you lost me, sorry ;)

**Comment by marcus433** [comment]
Sorry haha. So browserbox issues a SELECT command. It is my understanding that all updates from then on have relation to that select command thus multiple folders cannot be listened to without a new listener. The second issue I ran into is browserbox defines a selectedMailbox variable. When data is retrieved as an update the data doesn't contain the path on which it happened. Browserbox simply uses the selectedMailbox as the path as it knows it's the only mailbox connected. Disregarding the 1st issue and assuming multiple folders can indeed be listened to the browserbox would have an array of selected mailboxes. How would it know which item in the array to attach to an update as its path?



—

**Comment by andris9** [comment]
You can have only one *SELECTed* mailbox at a time and all FETCH commands you issue or EXPUNGE/EXISTS responses you get are related to that mailbox. So if you need to listen for several folders you need to create a new BrowserBox instance against every one of these. 

There is a limit though – for example Gmail limits active connections for a single user to 10. So if the user has Thunderbird open in one computer and this already allocates 5 connections, then you have only 5 connections left you could use before Gmail starts rejecting your logins. So if the user has 100 mailboxes, you can't use this approach or alternatively listen for the 5 most important mailboxes and ignore the rest.

The second approach would be to poll STATUS commands. Start listening on INBOX which would get the most new messages anyway and periodically run STATUS command against every other mailbox – if something is changed with the folder, SELECT it and see what is new.

In case of Gmail there's a third and better way – do not select INBOX but the "All Mail" mailbox (the one that has `specialFlags` set to `\All`). This mailbox includes all messages for the user except the messages in Trash and Junk. To get the actual folder path where the message is located ("All Mail" is a virtual folder), see the [X-GM-LABELS](https://developers.google.com/gmail/imap_extensions#access_to_gmail_labels_x-gm-labels) attribute. BrowserBox does not support the X-GM-EXT1 extension required for this attribute but it should be fairly easy to implement if you want to patch BrowserBox yourself.

Anyway, this is out of scope for imap-client, so I'll close the issue.

**Comment by marcus433** [comment]
Thanks for the response! I'll look into it



—

**Comment by felixhammerl** [comment]
still, we could modify the listening connection to continually fire status
commands for all the folders. needs a patch in browserbox, though. maybe
marcus wants to dive into that ;)

**Comment by marcus433** [comment]
I am currently looking into modifying the listening connection for continually firing STATUS
